#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : processor-trace
Version  : 2.0
Release  : 8
URL      : https://github.com/01org/processor-trace/archive/v2.0.tar.gz
Source0  : https://github.com/01org/processor-trace/archive/v2.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: processor-trace-lib
Requires: processor-trace-license
BuildRequires : buildreq-cmake

%description
Intel(R) Processor Trace Decoder Library
========================================

%package dev
Summary: dev components for the processor-trace package.
Group: Development
Requires: processor-trace-lib
Provides: processor-trace-devel

%description dev
dev components for the processor-trace package.


%package lib
Summary: lib components for the processor-trace package.
Group: Libraries
Requires: processor-trace-license

%description lib
lib components for the processor-trace package.


%package license
Summary: license components for the processor-trace package.
Group: Default

%description license
license components for the processor-trace package.


%prep
%setup -q -n processor-trace-2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533658303
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1533658303
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/processor-trace
cp LICENSE %{buildroot}/usr/share/doc/processor-trace/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libipt.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libipt.so.2
/usr/lib64/libipt.so.2.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/processor-trace/LICENSE
