#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : processor-trace
Version  : 2.0.5
Release  : 12
URL      : https://github.com/intel/libipt/archive/v2.0.5/libipt-2.0.5.tar.gz
Source0  : https://github.com/intel/libipt/archive/v2.0.5/libipt-2.0.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: processor-trace-lib = %{version}-%{release}
Requires: processor-trace-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
Intel(R) Processor Trace Decoder Library
========================================

%package dev
Summary: dev components for the processor-trace package.
Group: Development
Requires: processor-trace-lib = %{version}-%{release}
Provides: processor-trace-devel = %{version}-%{release}
Requires: processor-trace = %{version}-%{release}

%description dev
dev components for the processor-trace package.


%package lib
Summary: lib components for the processor-trace package.
Group: Libraries
Requires: processor-trace-license = %{version}-%{release}

%description lib
lib components for the processor-trace package.


%package license
Summary: license components for the processor-trace package.
Group: Default

%description license
license components for the processor-trace package.


%prep
%setup -q -n libipt-2.0.5
cd %{_builddir}/libipt-2.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643132157
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1643132157
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/processor-trace
cp %{_builddir}/libipt-2.0.5/LICENSE %{buildroot}/usr/share/package-licenses/processor-trace/5521fe0db6debc7c7b3e474f1205cad7313660e3
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/intel-pt.h
/usr/lib64/libipt.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libipt.so.2
/usr/lib64/libipt.so.2.0.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/processor-trace/5521fe0db6debc7c7b3e474f1205cad7313660e3
